### ISSUE TITLE
Depth is not handled in the right way 

### ISSUE THREAD

**Issue by MatsA** [Thomas-GeDaD/Seatalk1-Raspi-reader#1]
Please check glenn:s comment https://forum.openmarine.net/showthread.php?tid=2774&pid=15493#pid15493

**Comment by Thomas-GeDaD** [comment]
I check this...

**Comment by Thomas-GeDaD** [comment]
https://github.com/Thomas-GeDaD/Seatalk1-Raspi-reader/commit/11328b8393310b9ff8db3133d9fed83e5c784e3c

**Comment by Thomas-GeDaD** [comment]
Hve fix this issue
now on the first character a 0 is added if there is only a single digit.
should I make a pullrequest to signalk or can you do this?

**Comment by Thomas-GeDaD** [comment]
https://github.com/SignalK/signalk-server-node/pull/1097
please check again... ;-)

**Comment by MatsA** [comment]
Thanks for quick handling! Just a heads up for another change which is done #1096 https://github.com/SignalK/signalk-server-node/pull/1096

**Comment by Thomas-GeDaD** [comment]
https://github.com/Thomas-GeDaD/Seatalk1-Raspi-reader/commit/fc5b6c26543303e8d281c2262b4186e3051e87b5
have add this too. Thanks...
