### ISSUE TITLE
struct.error: unpack requires a string argument of length 16

### ISSUE THREAD

**Issue by barrymac** [Thomas-GeDaD/Seatalk1-Raspi-reader#3]
Thanks for your efforts, I'm trying to get this working with an opto-coupler circuit as documented in signalk repository [here](https://github.com/SignalK/signalk-server/blob/master/Seatalk(GPIO).md).

I get the following error when I run the script on the GPIO pin that I have plugged in. I presume the hardware side is ok as I get no response when I use another port or change some configuration parameters to wrong values. 

```
Traceback (most recent call last):
  File "STALK_read.py", line 39, in <module>
    out=(st1read.bb_serial_read(gpio))
  File "/usr/lib/python2.7/dist-packages/pigpio.py", line 4407, in bb_serial_read
    _pigpio_command_nolock(self.sl, _PI_CMD_SLR, user_gpio, 10000))
  File "/usr/lib/python2.7/dist-packages/pigpio.py", line 1008, in _pigpio_command_nolock
    dummy, res = struct.unpack('12sI', sl.s.recv(_SOCK_CMD_LEN))
struct.error: unpack requires a string argument of length 16
```

**Comment by Thomas-GeDaD** [comment]
Try it with sudo python3....

**Comment by barrymac** [comment]
Thanks for the fast response! After correcting some inconsistent tabs and spaces error, this of course worked. And I have to investigate hardware issues again :-P

**Comment by Thomas-GeDaD** [comment]
I have recheck the code. There is no tab issue. maybe a copy and paste issue?
